name: basic
on:
  push:
    branches: [ main ]
jobs:
  build: # 원하는 job의 이름을 지정한다
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo This is a "build" job area
  test:
    needs: build # 지정한 job이 종료된 후 실행
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo This is a "test" job area
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo This is a "depoy" job area
  
