name: terraform pipeline

on:
  push:
    branches: [ "terraform" ]
  workflow_dispatch: 
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: initializing terraform
        run: | 
          echo initalizing~~ 🚀🚀
          terraform init
          
      - name: planning terraform
        run: |
          echo planning~~ 🔥🔥
          terrafrom plan
