name: terraform pipeline

on:
  push:
    branches: [ "terraform" ]
  workflow_dispatch: 
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print variable
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} 🔥🔥
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} 🔥🔥
          echo ${{ env.AWS_REGION }} 🔥🔥
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ AWS_REGION }}
      - name: initializing terraform
        run: | 
          echo initalizing~~ 🚀🚀
          terraform init
      - name: planning terraform
        run: |
          echo planning~~ 🔥🔥
          terrafrom plan
